export const GET_PLANES_REQUEST = "GET_PLANES_REQUEST";
export const GET_PLANES_ASCENDING = "GET_PLANES_ASCENDING";
export const GET_PLANES_DESCENDING = "GET_PLANES_DESCENDING";
export const GET_PLANES_SUCCESS = "GET_PLANES_SUCCESS";
export const GET_PLANES_FAIL = "GET_PLANES_FAIL";

export const REMOVE_PLANE_REQUEST = "REMOVE_PLANE_REQUEST";

export const GET_PLANE_DETAILS_REQUEST = "GET_PLANE_DETAILS_REQUEST";
export const GET_PLANE_DETAILS_SUCCESS = "GET_PLANE_DETAILS_SUCCESS";
export const GET_PLANE_DETAILS_FAIL = "GET_PLANE_DETAILS_FAIL";
export const GET_PLANE_DETAILS_RESET = "GET_PLANE_DETAILS_RESET";

export const ADD_PLANE_REQUEST = "ADD_PLANE_REQUEST";
export const ADD_PLANE_SUCCESS = "ADD_PLANE_SUCCESS";
export const ADD_PLANE_FAIL = "ADD_PLANE_FAIL";
